#### IMPORTANDO LIBRERIAS

In [2]:
import numpy as np

In [2]:
lista=list(range(1,11))
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
arreglo= np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(arreglo)

numpy.ndarray

In [5]:
arreglo.dtype

dtype('int32')

In [6]:
np.array(arreglo, dtype=np.float32)#definiendo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [7]:
arreglo.astype(np.float32)#transformando

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [8]:
promedio=np.mean(arreglo)
promedio

In [9]:
mediana=np.median(arreglo)
mediana

In [10]:
desviacion_std=np.std(arreglo)
desviacion_std

SyntaxError: invalid syntax (3119732577.py, line 1)

In [ ]:
arreglo_de_unos=np.ones(10)
arreglo_de_unos

In [ ]:
arreglo_de_ceros=np.zeros(5)

In [ ]:
arreglo_de_ones=arreglo_de_unos.astype(int)
arreglo_de_ones

In [ ]:
arreglo_aleatoreo= np.random.rand()
arreglo_aleatoreo

In [ ]:
arreglo_alatoreo2=np.random.randint(1,101,5)
arreglo_alatoreo2

In [ ]:
matriz=np.random.rand(3,3)
matriz

In [ ]:
matriz2=np.random.randint(1,101(10,10))
matriz2